# Section A

## 1

In [2]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [9]:
list.append(6)
list

[1, 2, 3, 4, 5, 6]

In [12]:
list.extend([7,8])
list

[1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
list.insert(0,0)
list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
list.remove(2)
list

[0, 1, 3, 4, 5, 6, 7, 8]

In [15]:
list.pop()
list

[0, 1, 3, 4, 5, 6, 7]

In [16]:
list.clear()
list

[]

In [21]:
list=[1,2,3,4,5,6,7,8,9,4]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 4]

In [24]:
list.index(5)

4

In [25]:
list.count(4)

2

In [26]:
list.sort()
list

[1, 2, 3, 4, 4, 5, 6, 7, 8, 9]

In [27]:
list.reverse()
list

[9, 8, 7, 6, 5, 4, 4, 3, 2, 1]

## 2

In [28]:
tuple=("Aryan","Nevin","Anu")
tuple

('Aryan', 'Nevin', 'Anu')

In [30]:
tuple[2]=("Sabu")
tuple

TypeError: 'tuple' object does not support item assignment

In [31]:
## It cannot be renamed Tuple cannot be modified.To modify tuple it have to be converted to list

## 3

In [32]:
n={1,2,3,4,2,3,4,5,6,7}
n

{1, 2, 3, 4, 5, 6, 7}

In [33]:
## In a set duplicate elements are removed when printed because a set is always unique in elements

## 4

In [55]:
dict={'name':{'Adhila','Lekshmi','Noora'},
       'age':{25,26,28},
       'city':{'Banglore','Chennai','Mumbai'}}
dict


{'name': {'Adhila', 'Lekshmi', 'Noora'},
 'age': {25, 26, 28},
 'city': {'Banglore', 'Chennai', 'Mumbai'}}

In [56]:
dict.update({'age':{22,20,27}})
dict

{'name': {'Adhila', 'Lekshmi', 'Noora'},
 'age': {20, 22, 27},
 'city': {'Banglore', 'Chennai', 'Mumbai'}}

In [57]:
dict['email']={'adhila@gmail.com','noora@gmail.com','lekshmi@gmail.com'}
dict

{'name': {'Adhila', 'Lekshmi', 'Noora'},
 'age': {20, 22, 27},
 'city': {'Banglore', 'Chennai', 'Mumbai'},
 'email': {'adhila@gmail.com', 'lekshmi@gmail.com', 'noora@gmail.com'}}

## 5

In [58]:
age=int(input("Enter age"))
if (age>=18):
    print("Eligible to vote")
else:
    print("Not eligible to vote")
    

Enter age 15


Not eligible to vote


## 6

In [62]:
mark=int(input("Enter the mark"))
if (mark>=90):
    print("A")
elif(mark>=75):
    print("B")
elif(mark>=50):
    print("C")
else:
    print("Fail")

Enter the mark 24


Fail


## 7

In [68]:
n=int(input())
if(n>0):
    print("positive")
    if(n%2==0):
        print("even")
elif(n==0):
    print("Zero")
else:
    print("Negative")

 -9


Negative


# Section B

## 8

In [70]:
import numpy as np
num=np.array(5)
num

array(5)

In [86]:
num=np.array([1,2,3,4,5])
num

array([1, 2, 3, 4, 5])

In [88]:
num=np.array([[10,20,30],[40,50,60]])
num

array([[10, 20, 30],
       [40, 50, 60]])

## 9

In [99]:
a=np.array(np.random.randint(0,100,16).reshape(4,4))
a


array([[12, 91, 15, 76],
       [41, 76, 35,  3],
       [79, 25, 69, 69],
       [60, 16, 21, 93]])

## 10

In [100]:
import numpy as np
import pandas as pd
num=np.array(np.random.randint(0,50,9).reshape(3,3))
num

array([[ 1, 30, 20],
       [28, 13,  0],
       [41,  3, 37]])

In [104]:
df=pd.DataFrame(num,columns=('A','B','C'))
df

A   B   C
0   1  30  20
1  28  13   0
2  41   3  37

# Section C

## 11

In [169]:
dict1={'name':['Adhila','Noora','Adhila','Shanavas','Nevin','Anu','Lekshmi','Aryan','Akbar','Gizele'],
       'Age':[20,21,20,32,23,25,33,25,27,48],
       'City':['Banglore','Chennai','Banglore','Pune','Thrissur','Kolkata','Hyderabad','Goa','Kolkata','Rajasthan'],
       'Salary':[20000,np.nan,20000,50000,34000,54000,23000,34000,43400,10000]}
print(dict1)

{'name': ['Adhila', 'Noora', 'Adhila', 'Shanavas', 'Nevin', 'Anu', 'Lekshmi', 'Aryan', 'Akbar', 'Gizele'], 'Age': [20, 21, 20, 32, 23, 25, 33, 25, 27, 48], 'City': ['Banglore', 'Chennai', 'Banglore', 'Pune', 'Thrissur', 'Kolkata', 'Hyderabad', 'Goa', 'Kolkata', 'Rajasthan'], 'Salary': [20000, nan, 20000, 50000, 34000, 54000, 23000, 34000, 43400, 10000]}


In [170]:
df1=pd.DataFrame(dict1)
df1

name  Age       City   Salary
0    Adhila   20   Banglore  20000.0
1     Noora   21    Chennai      NaN
2    Adhila   20   Banglore  20000.0
3  Shanavas   32       Pune  50000.0
4     Nevin   23   Thrissur  34000.0
5       Anu   25    Kolkata  54000.0
6   Lekshmi   33  Hyderabad  23000.0
7     Aryan   25        Goa  34000.0
8     Akbar   27    Kolkata  43400.0
9    Gizele   48  Rajasthan  10000.0

In [171]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [172]:
df1.describe()

Age        Salary
count  10.000000      9.000000
mean   27.400000  32044.444444
std     8.553102  14995.591945
min    20.000000  10000.000000
25%    21.500000  20000.000000
50%    25.000000  34000.000000
75%    30.750000  43400.000000
max    48.000000  54000.000000

In [173]:
df1.iloc[:,[1,2]]

Age       City
0   20   Banglore
1   21    Chennai
2   20   Banglore
3   32       Pune
4   23   Thrissur
5   25    Kolkata
6   33  Hyderabad
7   25        Goa
8   27    Kolkata
9   48  Rajasthan

In [174]:
df1.drop(columns=['City'])

name  Age   Salary
0    Adhila   20  20000.0
1     Noora   21      NaN
2    Adhila   20  20000.0
3  Shanavas   32  50000.0
4     Nevin   23  34000.0
5       Anu   25  54000.0
6   Lekshmi   33  23000.0
7     Aryan   25  34000.0
8     Akbar   27  43400.0
9    Gizele   48  10000.0

In [175]:
df1.isnull().sum()

name      0
Age       0
City      0
Salary    1
dtype: int64

In [176]:
df1['Salary'].fillna(df1['Salary'].mean())

0    20000.000000
1    32044.444444
2    20000.000000
3    50000.000000
4    34000.000000
5    54000.000000
6    23000.000000
7    34000.000000
8    43400.000000
9    10000.000000
Name: Salary, dtype: float64

In [178]:
df1.duplicated().sum()

1

In [179]:
df1.drop_duplicates()

name  Age       City   Salary
0    Adhila   20   Banglore  20000.0
1     Noora   21    Chennai      NaN
3  Shanavas   32       Pune  50000.0
4     Nevin   23   Thrissur  34000.0
5       Anu   25    Kolkata  54000.0
6   Lekshmi   33  Hyderabad  23000.0
7     Aryan   25        Goa  34000.0
8     Akbar   27    Kolkata  43400.0
9    Gizele   48  Rajasthan  10000.0